language: node_js
node_js:
  - "5.10"
install:
  - npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - jdk_switcher use oraclejdk8
  - npm run test
branches:
  only:
  - master
